### PR TITLE
Fixes for builds on Ubuntu 22.10

### PR DESCRIPTION
**Pull request by dboddie**
Maybe https://bitbucket.org/inferno-os/inferno-os/pull-requests/17
and https://bitbucket.org/inferno-os/inferno-os/pull-requests/7
are better candidates to do more or less the same thing?

### CODE REVIEW

**Comment by forsyth** [comment]
sorry it's my fault, trying to maintain links and them not just vanishing,
but changes should appear on github. whether it tells me about them is
something else again.

**Comment by dboddie** [comment]
No worries. Some of the changes here are obsolete, I think. Edouard's changes (#13) are closer to what's needed, if not all the way there.

**Comment by forsyth** [comment]
I should just give you both commit whatever-they-call-them, so you can
update it at will

**Comment by dboddie** [comment]
Pull request #21 does what's necessary for me on Debian 12, so I'm retiring this one.

**Comment by forsyth** [comment]
ok, i've done that

**Pull request closed without merging**
